### ISSUE TITLE
Reconstructing Bezier Surfaces

### ISSUE THREAD

**Issue by wanghanxiao123** [bizerfr/BPNet#4]
Hello,

I am currently working on a project involving point cloud data and Bezier surfaces reconstruction. After exploring your BPNet, I have a specific query that I'm hoping to get some insights on.

Is it possible to use the output parameters  obtained from BPNet to reconstruct Bezier surfaces from point cloud data? If yes, could you provide some guidance or reference materials on how this can be achieved effectively using your system?

Looking forward to your insights.

Thank you for your time and assistance.

**Comment by bizerfr** [comment]
Hello,

We didn't use the direct output uv parameters to reconstruct the Bézier patch. Instead, we use Delaunay surface reconstruction to interpolate a mesh from the segmented patch and then use the parameterization method to recompute the uv parameters. We just use the least squares to fit the linear Bézier patch. The reason is that BPNet predicts the rational Bézier patch, but for Bézier surface reconstruction, reconstructing linear Bézier is more realistic. 

Best regards,

**Comment by bizerfr** [comment]
> Hello,
> 
> I am currently working on a project involving point cloud data and Bezier surfaces reconstruction. After exploring your BPNet, I have a specific query that I'm hoping to get some insights on.
> 
> Is it possible to use the output parameters obtained from BPNet to reconstruct Bezier surfaces from point cloud data? If yes, could you provide some guidance or reference materials on how this can be achieved effectively using your system?
> 
> Looking forward to your insights.
> 
> Thank you for your time and assistance.

Hello,

We didn't use the direct output uv parameters to reconstruct the Bézier patch. Instead, we use Delaunay surface reconstruction to interpolate a mesh from the segmented patch and then use the parameterization method to recompute the uv parameters. We just use the least squares to fit the linear Bézier patch. The reason is that BPNet predicts the rational Bézier patch, but for Bézier surface reconstruction, reconstructing linear Bézier patch is more realistic.

Best regards,
